# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Check Server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v2
      with:
        java-version: '16'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name : Download Server Installer
      run: |
       mkdir server
       cd server
       curl https://maven.minecraftforge.net/net/minecraftforge/forge/1.17.1-37.0.58/forge-1.17.1-37.0.58-installer.jar -o forge-installer.jar
    - name: Install Server
      run: |
       cd server
       java -jar forge-installer.jar --installServer
    - name: Copy Files
      run: |
       cd server
       cp libraries/net/minecraft/server/1.17.1/server-1.17.1.jar ./minecraft_server.1.17.1.jar
       cp libraries/net/minecraftforge/forge/1.17.1-37.0.58/forge-1.17.1-37.0.58-server.jar ./forge-server.jar
    - name: Setting Eula
      run: |
       cd server
       echo "eula=true" > eula.txt
    - name: Start Server 
      id: runningserver
      run: |
       cd server
       echo "::set-output name=forge-server-output::$(java -jar forge-server.jar nogui)\n"
       stop
      continue-on-error: true
    - name: Check Server has started successfully
      id: result
      if: contains(join(steps.runningserver.outputs.*,'\n'), 'For help, type') == false
      run: echo "-1"
      
